In [1]:
import torch

In [2]:
torch.randn(10,2)

tensor([[ 0.2751, -0.7410],
        [-0.2994, -0.3890],
        [ 1.5147,  1.0806],
        [-1.2030,  0.3897],
        [ 1.6549,  0.5882],
        [ 0.9342,  0.0822],
        [ 0.0176,  0.1284],
        [-0.7174, -1.0407],
        [-0.2207, -1.1728],
        [ 0.3348, -0.3242]])

In [3]:
import numpy as np
arry=np.array([[1,2,5,2],[4,5,13,3]])

In [4]:
tensor1=torch.tensor(arry)
tensor2=torch.tensor([1,2,4,4,2,5,1,52,6,23])
tensor3=torch.arange(6)

In [26]:

tensor3=tensor3.reshape(2,3)
print(tensor3)
tensor3[:,1:3]

tensor([[0, 1, 2],
        [3, 4, 5]])


tensor([[1, 2],
        [4, 5]])

In [29]:
tensor4=torch.arange(15)
tensor4=tensor4.reshape(3,5)
tensor4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [33]:
tensor4[:,1:2]

tensor([[ 1],
        [ 6],
        [11]])